@startuml
title Cycle de vie d'une demande (CustomerProblem)
 
skinparam titleFontSize 12 
 
skinparam state {
startColor #666666
endColor #666666
arrowColor #666666
borderColor #666666
fontSize 11
}
 
skinparam note {
fontSize 11
fontColor white
backgroundColor #45B8EF
borderColor white
}

[*] --> Opened
[*] --> Closed
Opened -> Closed
Opened -> Cancelled
Closed --> [*]
Cancelled --> [*]

@enduml
